# 1 - Prepare the lidar point cloud
prepare_data.py:
  working_dir: /home/gsalamin/Documents/project_data/rooftops
  pcd_dir: initial/LiDAR/2019
  inputs:
    pcd_tiles: initial/LiDAR/Emprises tuiles Lidar 2019.shp
    shp_roofs: initial/vectors/SHP_CAD_BATIMENT_HORSOL_TOIT/CAD_BATIMENT_HORSOL_TOIT.shp
  output_dir: processed/PCD_segmentation
  filters:
    egid: 1013180
    filter_class: False
    class_number: 6                 # 6: Building class
    filter_roof: True             # Remove all the point below the roof altitude
    distance_buffer: 2.0            #m, buffer value
  visualisation: false

# 2 - Point Cloud plane segmentation and clustering
pcd_segmentation.py: 
  working_dir: /home/gsalamin/Documents/project_data/rooftops
  input_dir: processed/PCD_segmentation
  output_dir: processed/PCD_segmentation
  egid: 1013180
  segmentation:
    plane:
      number_plane: 2
      distance_threshold: 0.1
      ransac: 3
      iteration: 1000
      eps: 1.0
      min_points: 5
    cluster:
      eps: 0.5
      min_points: 5
  visualisation: false

# 3 - 2D vectorisation of segmented 3D point cloud 
vectorization.py:  
  working_dir: /home/gsalamin/Documents/project_data/rooftops
  input_dir: processed/PCD_segmentation
  output_dir: processed/PCD_segmentation
  egid: 1013180
  epsg: 2056
  area_threshold: 50        # m2, Segmented polygon area threshold. Below this value the vectorized polygon in will be classified as object and not plane  
  alpha_shape: 2.0          # Alpha parameter used with the alpha shape algorithm used to define a bounding polygon around a group of points 
  visualisation: False

# 4 - Evaluate the results
assess_results.py: 
  working_dir: /home/gsalamin/Documents/project_data/rooftops
  input_dir: processed/PCD_segmentation
  output_dir: final/PCD_segmentation
  gt: ground_truth/EGID1013180/CAD_BATIMENT_HORSOL_OCCUPATION_EGID1013180.gpkg
  egid: 1013180