mask_for_buildings.py:
  working_dir: C:\Users\gwena\Documents\STDL\2_En_cours\occupation-toitures\02_Data
  roofs: processed/CAD_BATIMENT_HORSOL_TOIT_SP_merge/CAD_BAT_HORSOL_TOIT_SP_merge.gpkg
  image_folder: initial/images/true_ortho_2019
  transparency: True


get_lidar_infos.py:
  working_dir: C:\Users\gwena\Documents\STDL\2_En_cours\occupation-toitures\02_Data
  input_dir: initial/LiDAR
  overwrite: False

rasterize_intensity.py:
  working_dir: C:\Users\gwena\Documents\STDL\2_En_cours\occupation-toitures\02_Data
  input_dir: initial/LiDAR
  overwrite: False
  parameters:
    method: idw       # Interpolation method. Supported values: idw (Inverse Distance Weighting), nnb (Nearest Neighbour Interpolation) 
    resolution: 0.3   # Output resolution
    radius: 0.3       # Search radius
    returns: first    # Point return types to include. Supported values: all, first, last


rasterize_roughness.py:
  working_dir: C:\Users\gwena\Documents\STDL\2_En_cours\occupation-toitures\02_Data
  input_dir: initial/LiDAR
  overwrite: False
  make_dem: True
  parameters_dem: 
    resolution: 0.3   # Output resolution
    radius: 0.3       # Search radius
    min_z: 325        # Minimum elevation for inclusion in the interpolation
    max_z: 525        # Maximum elevation for inclusion in the interpolation
    max_edge: 25      # Maximum triangle edge length
  make_rgh: True
  parameters_rgh:
    min_scale: 1      # Minimum search radius
    max_scale: 2      # Maximum search radius
    step: 1           # Step size (int > 1)


filter_surfaces_by_attributes.py:
  debug_mode: False
  check_tiles: False
  working_dir: C:\Users\gwena\Documents\STDL\2_En_cours\occupation-toitures\02_Data
  input_dir_images: processed/lidar/rasterized_lidar
  lidar_tiles: initial/LiDAR/Emprises tuiles Lidar 2019.shp
  roofs: initial/vector/SHP_CAD_BATIMENT_HORSOL_TOIT/CAD_BATIMENT_HORSOL_TOIT.shp


filter_for_objects.py:
  debug_mode: False
  working_dir: C:\Users\gwena\Documents\STDL\2_En_cours\occupation-toitures\02_Data
  input_dir_images: processed/lidar/rasterized_lidar/intensity
  lidar_tiles: initial/LiDAR/Emprises tuiles Lidar 2019.shp
  roofs: processed/roofs/roofs.gpkg
  roofs_layer: roof_occupation
  kernel: False
  parameters:
    procedure: ds  # possible values: sd or ds
    rdp: True


random_forest.py:
  working_dir: C:\Users\gwena\Documents\STDL\2_En_cours\occupation-toitures\02_Data
  gt_file: verifications/LiDAR_products/right_classifications_lidar_products.gpkg
  layer_ocen: ocen_classification
  layer_ocan: ocan_classification
  predictions_file: processed/roofs/roofs.gpkg
  predictions_layer: roof_occupation_for_RF


segment_objects.py:
  debug_mode: True
  working_dir: C:\Users\gwena\Documents\STDL\2_En_cours\occupation-toitures\02_Data
  input_dir_images: processed/lidar/rasterized_lidar/intensity
  lidar_tiles: initial/LiDAR/Emprises tuiles Lidar 2019.shp
  roofs: processed/roofs/roofs.gpkg
  roofs_layer: roof_occupation
  method: slic   # possible values:  felzenszwalb, quickshift, slic, watershed,
  save_normalized_intensity: True


assess_classif_surfaces.py:
  working_dir: C:\Users\gwena\Documents\STDL\2_En_cours\occupation-toitures\02_Data
  gt_file: verifications/LiDAR_products/right_classifications_lidar_products.gpkg
  layer_ocen: ocen_classification
  layer_ocan: ocan_classification
  predictions_file: processed/roofs/roofs.gpkg
  predictions_layer: roof_occupation
  