# 1 - Prepare the lidar point cloud
prepare_data.py:
  working_dir: /home/gsalamin/Documents/project_data/rooftops
  pcd_dir: initial/LiDAR/2019
  inputs:
    pcd_tiles: initial/LiDAR/Emprises tuiles Lidar 2019.shp
    shp_roofs: initial/vectors/SHP_CAD_BATIMENT_HORSOL_TOIT/CAD_BATIMENT_HORSOL_TOIT.shp
    egids: EGID_list.txt
  output_dir: processed/PCD_segmentation
  filters:
    filter_class: False
    class_number: 6                 # 6: Building class
    filter_roof: True             # Remove all the point below the roof altitude
    distance_buffer: 1.0            #m, buffer value
  visualisation: false

# 2 - Point Cloud plane segmentation and clustering
pcd_segmentation.py: 
  working_dir: /home/gsalamin/Documents/project_data/rooftops
  input_dir: processed/PCD_segmentation
  output_dir: processed/PCD_segmentation
  egids: EGID_list.txt
  segmentation:
    planes:
      number_planes: 3
      distance_threshold: 0.1
      ransac: 3
      iterations: 1000
      eps: 1.0
      min_points: 5
    clusters:
      eps: 0.5
      min_points: 5
  visualisation: false

# 3 - 2D vectorisation of segmented 3D point cloud 
vectorization.py:  
  working_dir: /home/gsalamin/Documents/project_data/rooftops
  input_dir: processed/PCD_segmentation
  output_dir: processed/PCD_segmentation
  egids: EGID_list.txt
  epsg: 2056
  area_threshold: 
    min: 5        # m2, threshold for the area of the segmented sections. Below this value the vectorized polygon in will be classified as object and not plane
    max: 25       # m2, threshold for the area of the segmented objects. Above this value the vectorized object in will be classified as plane and not object
  alpha_shape: 2.0          # Alpha parameter used with the alpha shape algorithm used to define a bounding polygon around a group of points 
  visualisation: False

# 4 - Evaluate the results
assess_results.py: 
  working_dir: /home/gsalamin/Documents/project_data/rooftops
  output_dir: processed/PCD_segmentation
  detections: processed/PCD_segmentation/all_EGID_occupation.gpkg
  gt: ground_truth/EGID_occupation.gpkg
  egids: EGID_list.txt
  method: one-to-one


# 2 & 3 & 4 - Optimization of the hyperparameters
optimize_hyperparam_LiDAR.py:
  working_dir: /home/gsalamin/Documents/project_data/rooftops/processed/PCD_segmentation
  egids: ../../EGID_list.txt
  gt: ../../ground_truth/EGID_occupation.gpkg
  detections: all_EGID_occupation.gpkg
  epsg: 2056
  parameters:
    segmentation:
      planes:
        number_planes: 3
        distance_threshold: 0.1
        ransac: 3
        iterations: 1000
        eps: 1.0
        min_points: 5
      clusters:
        eps: 0.5
        min_points: 5
    area_threshold: 
      min: 5        # m2. Below this value the vectorized polygon in will be classified as object and not plane
      max: 25       # m2. Above this value the vectorized object in will be classified as plane and not object
    alpha_shape: 2          # Alpha parameter used with the alpha shape algorithm used to define a bounding polygon around a group of points 
  method: one-to-one
  visualisation: None
