assess_feedbacks.py:
  working_directory: .
  input_folder: input
  output_folder: 'output/expert_control'
  output_file: experts_feedbacks
  expert: <EXPERT> # Add the name of the result's reviewer
  append: False # If True new results will be add to the existing file otherwise data will be overwritten