# 1 - Prepare the lidar point cloud
prepare_data.py:
  working_dir: /home/username/project_path       # !!! Absolute path needed to work with WhiteBox Tools!!!
  pcd_dir: inputs/LiDAR/2019
  inputs:
    pcd_tiles: inputs/LiDAR/Emprises tuiles Lidar 2019.shp
    shp_roofs: inputs/vectors/SHP_CAD_BATIMENT_HORSOL_TOIT/CAD_BATIMENT_HORSOL_TOIT.shp
    egids: EGIDs_GT_training.csv
  output_dir: outputs/PCD_segmentation/pitched_roofs
  filters:
    roof_inclination: pitched
    filter_class: False
    class_number: 6                 # 6: Building class
    filter_roof: True               # Remove all the point below the roof altitude
    distance_buffer: 2.0            # m, buffer value
  overwrite: False
  visualisation: False


# 2 - Point Cloud plane segmentation and clustering
pcd_segmentation.py: 
  working_dir: outputs/PCD_segmentation/pitched_roofs
  output_dir: per_EGID_data
  input_dir_pcd: per_EGID_data
  egids: completed_egids.csv
  segmentation:
    planes:
      distance_threshold: 0.07      # Max distance a point can be from the plane model, and still be considered an inlier
      ransac: 3                     # Number of inputs points to be considered inliers in each iteration
      iterations: 11500             # Number of iterations
      eps: 12                       # Density parameter that is used to find neighbouring points
      min_points: 550              # Minimum number of points to form a plane
    clusters:
      eps: 0.79                     # Density parameter that is used to find neighbouring points
      min_points: 8                # Minimum number of points to form a cluster
  visualisation: False


# 3 - 2D vectorisation of segmented 3D point cloud 
vectorization.py:  
  working_dir: outputs/PCD_segmentation/pitched_roofs
  output_dir: .
  input_dir_pcd: per_EGID_data
  egids: completed_egids.csv
  roofs: CAD_BATIMENT_HORSOL_TOIT_EGID_subset.shp
  epsg: 2056
  area_threshold: 
    min: 11        # m2, minimum area of the segmented sections, below the vectorized polygon in will be classified as object
    max: 240       # m2, maximum area of the segmented objects, above the vectorized object in will be classified as plane
  alpha_shape: 2.4          # Alpha parameter used in the alpha shape algorithm to define a bounding polygon around a group of points 
  visualisation: False


# 4 - Evaluate the results
assess_results.py: 
  working_dir: .
  output_dir: outputs/PCD_segmentation/pitched_roofs
  detections: outputs/PCD_segmentation/pitched_roofs/all_EGID_occupation.gpkg
  ground_truth: ground_truth/partition/roofs_STDL_proofed_2023-11-10_LiDAR_training.shp
  egids: outputs/PCD_segmentation/pitched_roofs/completed_egids.csv
  roofs: outputs/PCD_segmentation/pitched_roofs/CAD_BATIMENT_HORSOL_TOIT_EGID_subset.shp
  method: fusion
  threshold: 0.1
  additional_metrics: True
  visualisation: True
  object_attributes:
    parameters: ['area', 'nearest_distance_centroid'] # Choice between: 'area', 'nearest_distance_border', 'nearest_distance_centroid' 
    area_ranges:  [[0,0.5], [0.5,1], [1,5], [5,10], [10,50], [50,100], [100, 750]] 
    distance_ranges: [[0,1], [1,5], [5,10], [10, 100]]


# 2 & 3 & 4 - Optimization of the hyperparameters
optimize_hyperparam_LiDAR.py:
  working_dir: outputs/PCD_segmentation/pitched_roofs
  output_dir: optimization
  input_dir_pcd: per_EGID_data
  egids: completed_egids.csv
  ground_truth: ../../../ground_truth/partition/roofs_STDL_proofed_2023-11-10_LiDAR_training.shp
  roofs: CAD_BATIMENT_HORSOL_TOIT_EGID_subset.shp
  epsg: 2056
  parameters:
    alpha_shape: 2.4
  method: fusion
  visualisation: None