#####################################################################
###########     configuration file proj-rooftops     ############ 
#####################################################################


# 1-Prepare the lidar point cloud
prepare_data.py:
  working_folder: "/mnt/data-02/cherny/git/proj-rooftops"
  input_data_folder: "data/LiDAR"
  input_shape_folder: "data/vectors/SHP_CAD_BATIMENT_HORSOL_TOIT/"
  output_folder: "output/PCD_segmentation"
  dataname: "2499000_1115000"
  pcd_type: "las"
  egid: 2034760
  shpname: "CAD_BATIMENT_HORSOL_TOIT.shp"
  filters:
    filter_class: 'True'
    class_number: 6
    filter_roof: 'True'

# 2-Point Cloud plane segmentation and clustering
plane_segmentation.py: 
  input_folder: "../output/PCD_segmentation/"
  output_folder: "../output/PCD_segmentation/"
  dataname: "2499000_1115000_EGID2034760"
  visu: 'True'

# 3-2D vectorisation of segmented 3D point cloud 
polygonize.py:
  input_folder: "../output/PCD_segmentation/"
  output_folder: "../output/PCD_segmentation/"
  dataname: "2499000_1115000_EGID2034760"
  epsg: 2056
  area_threshold: 50
  visu: 'False'

# 4-Evaluate the results
assess_results.py: 
  input_folder: "../output/PCD_segmentation/"
  output_folder: "../output/PCD_segmentation/"
  dataname: "2499000_1115000_EGID2034760"
  shpname: "2499000_1115000_EGID2034760_occupation.gpkg"
  gt_shapefile: "../data/processed/GT/EGID2034760/CAD_BATIMENT_HORSOL_OCCUPATION_EGID2034760.gpkg"
  egid: 2034760