# 1 - Combination of pcd and
combine_results.py:  
  working_dir: .
  img_seg: outputs/image_segmentation/training_equal_precision_recall/vectors/roof_segmentation.gpkg
  pcd_seg: outputs/pcd_segmentation/outputs/final_detections_pcd_seg.gpkg
  layer_pcd: detections_pcd_seg 
  roofs: inputs/vectors/SHP_CAD_BATIMENT_HORSOL_TOIT/CAD_BATIMENT_HORSOL_TOIT_EGID.shp
  egids: inputs/ground_truth/egid/EGIDs_GT_full.csv
  output_dir: outputs/results_combination/training/config2


# 2 - Evaluate the results
assess_results.py:  
  working_dir: .
  roofs: inputs/vectors/SHP_CAD_BATIMENT_HORSOL_TOIT/CAD_BATIMENT_HORSOL_TOIT.shp
  # roofs: inputs/image_segmentation/ground_truth/occupation/custom/roofs_STDL_proofed_2023-11-13.shp
  ground_truth: inputs/ground_truth/occupation/custom/roofs_STDL_proofed_2023-11-13.shp
  egids: inputs/ground_truth/egid/EGIDs_GT_training_all_all.csv
  output_dir: outputs/results_combination/training/config2
  detections: roof_segmentation.gpkg
  method: fusion # Method choices 1: one-to-one, 2: one-to-many, 3: charges, 4: fusion 
  additional_metrics: True
  visualisation: True
  threshold: 0.1                 # Threshold value to consider that a detection overlaps a label
  object_attributes:
    parameters: ['area', 'nearest_distance_border'] # Choice between: 'area', 'nearest_distance_border', 'nearest_distance_centroid' 
    area_ranges:  [[0,0.5], [0.5,1], [1,5], [5,10], [10,50], [50,100], [100, 750]] 
    distance_ranges: [[0,1], [1,5], [5,10], [10, 100]]