# 1 - Results combination of pcd segmentation and img segmentation
combine_results_seg.py:  
  working_dir: .
  output_dir: outputs/results_combination/training/final_prec_eq_recall/
  img_seg: outputs/results_combination/training/final_prec_eq_recall/roof_segmentation.gpkg
  pcd_seg: outputs/results_combination/training/final_prec_eq_recall/final_detections_pcd_seg.gpkg
  layer_pcd: detections_pcd_seg 
  roofs: data/SHP_CAD_BATIMENT_HORSOL_TOIT/CAD_BATIMENT_HORSOL_TOIT_EGID.shp
  egids: data/EGIDs_GT_test.csv

# 2 - Evaluate the results
assess_results.py:  
  working_dir: .
  roofs: inputs/vectors/SHP_CAD_BATIMENT_HORSOL_TOIT/CAD_BATIMENT_HORSOL_TOIT.shp
  output_dir: outputs/results_combination/training/final_prec_eq_recall/sjoin
  ground_truth: inputs/ground_truth/occupation/custom/roofs_STDL_proofed_2023-11-13.shp
  egids: inputs/ground_truth/egid/EGIDs_GT_training_all_all.csv
  detections: outputs/results_combination/training/final_prec_eq_recall/roof_segmentation_sjoin.gpkg
  method: fusion                # methods: 'one-to-one', 'one-to-many', 'charges', 'fusion'
  additional_metrics: True      # compute metrics for given attributes (building type, roof type, object class, object attributes)
  threshold: 0.1                # threshold value (area) to consider that a detection overlaps a label
  object_attributes:
    parameters: [area, nearest_distance_centroid, roundness] # choices: 'area', 'nearest_distance_border', 'nearest_distance_centroid' 
    area_ranges:  [[0,0.5], [0.5,1], [1,5], [5,10], [10,50], [50,100], [100, 750]] 
    distance_ranges: [[0,1], [1,5], [5,10], [10, 100]]
    round_ranges: [[0,0.25], [0.25,0.5], [0.5,0.75], [0.75, 1.0]]
  visualization: True           # show plots

assess_area.py:
  working_dir: .
  roofs: inputs/vectors/SHP_CAD_BATIMENT_HORSOL_TOIT/CAD_BATIMENT_HORSOL_TOIT.shp
  ground_truth: inputs/ground_truth/occupation/custom/roofs_STDL_proofed_2023-11-13.shp
  egids: inputs/ground_truth/egid/EGIDs_GT_training_all_all.csv
  output_dir: outputs/results_combination/training/final_prec_eq_recall/combined
  detections: outputs/results_combination/training/final_prec_eq_recall/roof_segmentation_combined.gpkg
  method: fusion                # choices: 'one-to-one', 'one-to-many', 'charges', 'fusion'
  bins: [0, 25, 50, 75, 100]    # percentage of free area bin limits
  visualization: True           # show plots