assess_flai.py:  
  working_dir: C:\Users\gwena\Documents\STDL\2_En_cours\occupation-toitures\02_Data
  method: tile       # by tile or by EGID
  tiles: initial/LiDAR/Emprises tuiles Lidar 2019.shp
  gt: processed\manual_GT\merged_occupied_surface.shp
  detection: processed\tests\flai\2499000_1115000.shp