# 1 - Prepare the lidar point cloud
prepare_data.py:
  working_dir: "/mnt/data-02/cherny/git/proj-rooftops"
  pcd_dir: "data/LiDAR"
  shp_dir: "data/vectors/SHP_CAD_BATIMENT_HORSOL_TOIT/"
  output_dir: "output/PCD_segmentation/clean_branch"
  pcd_name: "2500000_1117000"
  pcd_ext: "las"
  egid: 1013180
  shp_roofs: "CAD_BATIMENT_HORSOL_TOIT.shp"
  filters:
    filter_class: 'True'
    class_number: 6
    filter_roof: 'True'

# 2-Point Cloud plane segmentation and clustering
plane_segmentation.py: 
  input_folder: "../output/PCD_segmentation/"
  output_folder: "../output/PCD_segmentation/"
  dataname: "2499000_1115000_EGID1013180"
  visu: 'True'

# 3 - 2D vectorisation of segmented 3D point cloud 
vectorization.py:  
  working_dir: "/mnt/data-02/cherny/git/proj-rooftops"
  input_dir: "output/PCD_segmentation"
  output_dir: "output/PCD_segmentation"
  pcd_name: "2499000_1117000"
  egid: 1013180
  epsg: 2056
  area_threshold: 50
  visualisation: "False"

# 4-Evaluate the results
assess_results.py: 
  input_folder: "../output/PCD_segmentation/"
  output_folder: "../output/PCD_segmentation/"
  dataname: "2499000_1117000_EGID1013180"
  shpname: "2499000_1117000_EGID1013180_occupation.gpkg"
  gt_shapefile: "../data/GT/EGID1013180/CAD_BATIMENT_HORSOL_OCCUPATION_EGID1013180.gpkg"
  egid: 1013180