# 1 - Prepare the lidar point cloud
prepare_data.py:
  working_dir: "/mnt/data-02/cherny/git/proj-rooftops"
  pcd_dir: "data/LiDAR"
  shp_dir: "data/vectors/SHP_CAD_BATIMENT_HORSOL_TOIT/"
  output_dir: "output/PCD_segmentation/clean_branch"
  pcd_name: "2500000_1117000"
  pcd_ext: "las"
  egid: 1013180
  shp_roofs: "CAD_BATIMENT_HORSOL_TOIT.shp"
  filters:
    filter_class: 'True'
    class_number: 6
    filter_roof: 'True'

# 2-Point Cloud plane segmentation and clustering
pcd_segmentation.py: 
  working_dir: "/mnt/data-02/cherny/git/proj-rooftops"
  input_dir: "output/PCD_segmentation"
  output_dir: "output/PCD_segmentation"
  pcd_name: "2499000_1117000"
  egid: 1013180
  segmentation:
    plane:
      number_plane: 2
      distance_threshold: 0.1
      ransac: 3
      iteration: 1000
      eps: 1.0
      min_points: 5
    cluster:
      eps: 0.5
      min_points: 5
  visualisation: "True"

# 3 - 2D vectorisation of segmented 3D point cloud 
vectorization.py:  
  working_dir: "/mnt/data-02/cherny/git/proj-rooftops"
  input_dir: "output/PCD_segmentation"
  output_dir: "output/PCD_segmentation"
  pcd_name: "2499000_1117000"
  egid: 1013180
  epsg: 2056
  area_threshold: 50                                    #m2, Segmented polygon area threshold. Below this value the vectorized polygon in will be classified as object and not plane  
  alpha_shape: 2.0                                      # Alpha parameter used with the alpha shape algorithm used to define a bounding polygon around a group of points 
  visualisation: "False"

# 4-Evaluate the results
assess_results.py: 
  input_folder: "../output/PCD_segmentation/"
  output_folder: "../output/PCD_segmentation/"
  dataname: "2499000_1117000_EGID1013180"
  shpname: "2499000_1117000_EGID1013180_occupation.gpkg"
  gt_shapefile: "../data/GT/EGID1013180/CAD_BATIMENT_HORSOL_OCCUPATION_EGID1013180.gpkg"
  egid: 1013180