filter_by_attributes.py:
  working_directory: C:/Users/gwena/Documents/STDL/2_En_cours/occupation-toitures/02_Data
  input_files:
    roofs: initial\vector\SHP_PRODUIT_CAD_BATI_3D\CAD_BATI3D_BASIC_TOIT.shp
    potential_solar_surfaces: initial\vector\SHP_OCEN_SOLAIRE_ID_SURFACE_BASE\OCEN_SOLAIRE_ID_SURFACE_BASE.shp
    heritage:
      ensembles: initial\vector\SHP_DPS_ENSEMBLE\DPS_ENSEMBLE.shp
      classement: initial\vector\SHP_DPS_CLASSEMENT\DPS_CLASSEMENT.shp
  parameters:
    house_vs_building: 10   # height limit in m
    houses:
      flat_vs_pitched: 10   # angle limit in degree
      flat_roofs:
        solar_area: 25      # surface limit in m2
      pitched_roofs:
        solar_area: 15      # surface limit in m2
    buildings:
      solar_area: 200       # surface limit in m2
    vegetation_area: 20     # surface limit in m2
    vegetation_inclination: 5    # 5% = 2.86° -> round up by 5, because we have the average slope