mask_for_buildings.py:
  working_dir: C:\Users\gwena\Documents\STDL\2_En_cours\occupation-toitures\02_Data
  roofs: processed/CAD_BATIMENT_HORSOL_TOIT_SP_merge/CAD_BAT_HORSOL_TOIT_SP_merge.gpkg
  layer: labelling subset
  image_folder: initial/images/true_ortho_2019


get_lidar_infos.py:
  working_dir: C:\Users\gwena\Documents\STDL\2_En_cours\occupation-toitures\02_Data
  input_dir: initial/LiDAR
  overwrite: False


rasterize_intensity.py:
  working_dir: C:\Users\gwena\Documents\STDL\2_En_cours\occupation-toitures\02_Data
  input_dir: initial/LiDAR
  overwrite: False
  parameters:
    method: idw
    res: 0.3
    radius: 0.3
    returns: 'first'


filter_surfaces_by_attributes.py:
  working_dir: C:\Users\gwena\Documents\STDL\2_En_cours\occupation-toitures\02_Data
  input_dir_images: processed/rasterized_lidar
  lidar_tiles: initial/LiDAR/Emprises tuiles Lidar 2019.shp
  roofs: initial/vector/SHP_CAD_BATIMENT_HORSOL_TOIT/CAD_BATIMENT_HORSOL_TOIT.shp