# 1 - Tiles generation
generate_tiles.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/occupation-toitures/02_Data
  image_dir: initial/images/true_ortho_2019
  output_dir: processed/OD
  tiles: initial/images/true_ortho_2019/Tuiles.shp
  roofs: initial/vectors/SHP_CAD_BATIMENT_HORSOL_TOIT/CAD_BATIMENT_HORSOL_TOIT.shp
  egids: EGIDs_full_GT.csv
  filters:
    building_type: all
    roof_inclination: all
  buffer: 1                  # m, Distance buffer around the rooftop shape (prevent to "cut" the rooftop border)
  mask: True                # Choose if a mask (by EGID) is applied to image to only keep the building visible
  overwrite: True
  obj_detection: True


# 2 - Prepare vector data
prepare_data.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/occupation-toitures/02_Data
  output_dir: processed/OD
  roofs: initial/vectors/SHP_CAD_BATIMENT_HORSOL_TOIT/CAD_BATIMENT_HORSOL_TOIT.shp
  egids: EGIDs_full_GT.csv
  ground_truth: ground_truth/roofs_STDL_proofed_2023-11-13.shp
  filters:
    building_type: all
    roof_inclination: all
    prepare_labels: True
    prepare_tiles: True
  buffer: 1


# 3 - Generate tilesets
generate_tilesets.py:
  debug_mode: 
    enable: False  # sample of tiles
    nb_tiles_max: 10
  working_directory: C:/Users/gwena/Documents/STDL/2_En_cours/occupation-toitures/02_Data/processed/OD
  datasets:
    aoi_tiles: bbox.gpkg
    ground_truth_labels: ground_truth_labels.gpkg
    orthophotos_web_service:
      type: folder
      url: images
      srs: "EPSG:2056"
  output_folder: .
  tile_size: 256 # per side, in pixels
  overwrite: False
  n_jobs: 10
  # seed: 2
  COCO_metadata:
    year: 2019
    version: 2.0
    description: True orthophotos du canton de Genève 2019
    contributor: DIT
    url: x
    license:
      name: x
      url: x