# 1 - Prepare the lidar point cloud
prepare_data.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/occupation-toitures/02_Data
  pcd_dir: initial/LiDAR
  inputs:
    pcd_tiles: initial/LiDAR/Emprises tuiles Lidar 2019.shp
    shp_roofs: initial/vectors/SHP_CAD_BATIMENT_HORSOL_TOIT/CAD_BATIMENT_HORSOL_TOIT.shp
    egids: EGIDs_GT_training.csv
  output_dir: processed/PCD_segmentation/pitched_roofs
  filters:
    # building_type: residential
    roof_inclination: pitched
    filter_class: False
    class_number: 6                 # 6: Building class
    filter_roof: True               # Remove all the point below the roof altitude
    distance_buffer: 1.0            # m, buffer value
  overwrite: False
  visualisation: False


# 2 - Point Cloud plane segmentation and clustering
pcd_segmentation.py: 
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/occupation-toitures/02_Data/processed/PCD_segmentation/pitched_roofs
  output_dir: per_EGID_data
  input_dir_pcd: per_EGID_data
  egids: completed_egids.csv
  segmentation:
    planes:
      # number_planes: 5            # Number of planes to expect
      distance_threshold: 0.07      # Max distance a point can be from the plane model, and still be considered an inlier
      ransac: 3                     # Number of initial points to be considered inliers in each iteration
      iterations: 11500             # Number of iterations
      eps: 12                       # Density parameter that is used to find neighbouring points
      min_points: 550              # Minimum number of points to form a plane
    clusters:
      eps: 0.79                     # Density parameter that is used to find neighbouring points
      min_points: 8                # Minimum number of points to form a cluster
  visualisation: False


# 3 - 2D vectorisation of segmented 3D point cloud 
vectorization.py:  
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/occupation-toitures/02_Data/processed/PCD_segmentation/pitched_roofs
  output_dir: .
  input_dir_pcd: per_EGID_data
  egids: completed_egids.csv
  roofs: CAD_BATIMENT_HORSOL_TOIT_EGID_subset.shp
  epsg: 2056
  area_threshold: 
    min: 11        # m2, minimum area of the segmented sections, below the vectorized polygon in will be classified as object
    max: 240       # m2, maximum area of the segmented objects, above the vectorized object in will be classified as plane
  alpha_shape: 2.4          # Alpha parameter used in the alpha shape algorithm to define a bounding polygon around a group of points 
  visualisation: False


# 2 & 3 & 4 - Optimization of the hyperparameters
optimize_hyperparam_LiDAR.py:
  working_dir: C:/Users/gwena/Documents/STDL/2_En_cours/occupation-toitures/02_Data/processed/PCD_segmentation
  output_dir: optimization
  input_dir_pcd: per_EGID_data
  egids: completed_egids.csv
  ground_truth: ../../ground_truth/partition/roofs_STDL_proofed_2023-11-10_LiDAR_training.shp
  roofs: CAD_BATIMENT_HORSOL_TOIT_EGID_subset.shp
  epsg: 2056
  parameters:
    alpha_shape: 2.4
  method: fusion
  visualisation: None