mask_for_buildings.py:
  transparency: true
  working_dir: /mnt/data-02/cherny/git/proj-rooftops/data/
  roofs: /mnt/data-02/cherny/git/proj-rooftops/data/SHP_CAD_BATIMENT_HORSOL_TOIT/CAD_BATIMENT_HORSOL_TOIT.shp
  layer: labelling subset
  image_folder: processed/roof_pictures
