mask_for_buildings.py:
  working_dir: /mnt/data-02/cherny/git/proj-rooftops/
  roofs: data/processed/CAD_BATIMENT_HORSOL_TOIT_SP_merge/CAD_BATIMENT_HORSOL_TOIT_SP_merge.gpkg
  layer: labelling subset
  image_folder: data/initial/images/true_ortho_2019